contentdir = "content"
layoutdir = "layouts"
publishdir = "../."
builddrafts = false
baseurl = "http://ernestas-poskus.github.io/"
languageCode = "en-us"
title = "Ernestas Po≈°kus.io"

[params]
  Description = "Gopher, Ruby techie, pragmatic & ambitious, - vicious vim hacker."
  disqusShortname = "ernestasposkusio"

[[menu.social]]
  url = "https://github.com/ernestas-poskus"
  name = "github.com/ernestas-poskus"

[[menu.social]]
  url = "https://twitter.com/ernestas_poskus"
  name = "twitter.com/ernestas_poskus"

[[menu.social]]
  url = "https://www.linkedin.com/in/ernestasposkus"
  name = "linkedin.com/in/ernestasposkus"
